Increment12
alphaonly/harvester pull request #7
Opened 2023-02-27 17:14 UTC by alphaonly

2023-03-06 16:55 UTC, Perederey requested changes
Код выглдяит хорошо, осталось его привести к стандартам Go.

Основыне комменатрии написал, плюс к этому go vet у тебя ругается, без него работу принять не могу

2023-03-06 16:55 UTC, Perederey commented on .gitignore
> +/cmd/tests/restycheck.go
тут пропустил конец-строки
это последовательность символов, обозначающая конец строки текста в коде. EOL важны для запросов для PR, поскольку они определяют, как текстовые файлы отображаются и обрабатываются в различных операционных системах.
Windows использует комбинацию символов (CR) и перевода строки (LF) для обозначения конца строки, в то время как Linux и macOS используют только символ перевода строки (LF).
Представь, если разработчик создает файл на Windows, а затем отправляет запрос на исправление с этим файлом, файл будет содержать CR+LF EOL. Но если этот файл затем будет извлечен и объединен в репозиторий на macOS, символы CR вызовут проблемы при редактировании)
По этой причине для PR важно, чтобы текстовые файлы были последовательны в использовании EOL.
IDE можно настроить чтобы перед запуском он добавлял такую штуку

2023-03-06 16:55 UTC, Perederey commented on cmd/agent/main.go
> +
Лишний пробел

2023-03-06 16:55 UTC, Perederey commented on cmd/agent/main.go
> +	defer cancel()
Я не совсем понял, а где ты делаешь обработку contex? Ты его создаешь, а где обрабатываешь?

2023-03-06 16:55 UTC, Perederey commented on cmd/agent/main.go
> +	ac.UpdateFromFlags()
тут можно применить pattern options.
https://medium.com/@perederei/option-functions-pattern-golang-d76f519b1d60

2023-03-06 16:55 UTC, Perederey commented on cmd/agent/main_test.go
> +		},
если делаешь табличный тест, то добавляй сразу несколько тестов

2023-03-06 16:55 UTC, Perederey commented on cmd/agent/main_test.go
> +			defer cancel()
а как ты ловишь context?

2023-03-06 16:55 UTC, Perederey commented on cmd/server/main.go
> +	}
с большой буквы писать нет смысла, плюс else не используется часто в go, попробуй уйти от else

2023-03-06 16:55 UTC, Perederey commented on cmd/server/main.go
> +	_handlers := &handlers.Handlers{
_ - Это тоже лишниее, так в гоу не делают просто handlers -

2023-03-06 16:55 UTC, Perederey commented on cmd/server/main_test.go
> +			if !assert.Equal(t, tt.want, err) {
обычно так не делают, смысла же особого нет получается, обычно используют еще один hanlder health/check  например, который возвращает 200 статус (некий ping) и сервер проверяется каждые 5 секунд например

2023-03-06 16:55 UTC, Perederey commented on cmd/tests/test.go
> +	dbURL := "postgres://postgres:mypassword@localhost:5432/yandex"
лучше бы это в конфиг вынести

2023-03-06 16:55 UTC, Perederey commented on internal/configuration/configuration.go
> +	case string:
подумай как избавится от case и switch, возможно variableValue может быть интерфейсом с методами GetValue, SetValue и так далее

2023-03-06 16:55 UTC, Perederey commented on internal/schema/schema.go
> +		switch e.MType {
тут тоже можно попробовать избавится от switch

2023-03-06 16:55 UTC, Perederey commented on internal/schema/schema.go
> +		panic(errors.New("name or type is empty"))
panic вызывать точо не стоит, лучше возвращай ошибку и ее обрабатывай

2023-03-06 16:55 UTC, Perederey commented on internal/schema/schema.go
> +		default:
лишняя конструкция, так как в условиях в этой же функции ты проверяешь ужена тип

2023-03-09 05:48 UTC, alphaonly commented on cmd/agent/main.go
> +	ac.UpdateFromFlags()
поправил

2023-03-09 05:52 UTC, alphaonly commented on cmd/agent/main.go
> +	defer cancel()
передаю контекст в го-рутины send и update, обрабатываю его там. не понял в чем вопрос.

2023-03-09 05:52 UTC, alphaonly commented on cmd/agent/main.go
> +
поправил

2023-03-09 14:18 UTC, alphaonly commented on cmd/server/main.go
> +	}
поправил

2023-03-09 14:19 UTC, alphaonly commented on cmd/server/main.go
> +	_handlers := &handlers.Handlers{
поправил

2023-03-09 14:27 UTC, alphaonly commented on .gitignore
> +/cmd/tests/restycheck.go
В целом, я тут недопонял. У меня goland на windows дома и visual studio на linux на работе и я ничего не заметил. Какие правильные символы нужно оставлять то?

2023-03-09 14:36 UTC, alphaonly commented on cmd/tests/test.go
> +	dbURL := "postgres://postgres:mypassword@localhost:5432/yandex"
Поправил. Файл случайно попал в коммиты

2023-03-09 14:42 UTC, alphaonly commented on internal/schema/schema.go
> +		panic(errors.New("name or type is empty"))
поправил

2023-03-10 09:03 UTC, alphaonly commented on internal/schema/schema.go
> +		default:
поправил

2023-03-10 09:04 UTC, alphaonly commented on cmd/agent/main_test.go
> +			defer cancel()
поправил

2023-03-10 10:31 UTC, alphaonly commented on cmd/server/main_test.go
> +			if !assert.Equal(t, tt.want, err) {
поправил

2023-03-10 12:15 UTC, alphaonly commented on cmd/agent/main_test.go
> +		},
поправил

2023-03-10 12:16 UTC, alphaonly commented on internal/configuration/configuration.go
> +	case string:
избавился, но по мне как  case лучше, не надо городить кучу реализаций и интерфейс,  kiss вроде бы

2023-03-10 13:42 UTC, alphaonly commented on internal/schema/schema.go
> +		switch e.MType {
Поправил

2023-03-13 22:54 UTC, Perederey commented on cmd/agent/main.go
> +	defer cancel()
Если вызывается сигнал context.Done() то где ты его ловишь?

2023-03-13 23:02 UTC, Perederey reviewed
Уже код лучше, написал комментарий на исправления основные.

Но пока не могу присесть работу, у тебя не работают  тесты

2023-03-13 23:02 UTC, Perederey commented on cmd/agent/main.go
> +		case <-ctx.Done():
Все теперь увидел про контекст 💪

2023-03-13 23:02 UTC, Perederey commented on cmd/agent/main.go
> +			break forLabel
Но это немного странная конструкция с brake, можно ли ее как-то упросить?

2023-03-13 23:02 UTC, Perederey commented on cmd/agent/main_test.go
> +			want:  true,
А на want = false?

2023-03-13 23:02 UTC, Perederey commented on cmd/server/main.go
> +	_server := server.New(configuration, externalStorage, handlers)
Говорили о том, чтобы вот так не писать названия переменных 
Просто s, srv например

2023-03-13 23:02 UTC, Perederey commented on cmd/server/main_test.go
> +			name: "test#1 - Positive: server works",
П тут не поправил/добавил тестов

2023-03-13 23:02 UTC, Perederey commented on internal/agent/workerpool/workerpool.go
> +				break forLabel
А почему бы не завершить работу? Почему нужно бесконечно уходить снова в цикл? В чем тогда смысл тут использовать context?

2023-03-13 23:02 UTC, Perederey commented on internal/configuration/configuration.go
> +	EnvChanged    map[string]bool
Немного сложный путь, но можно и так

2023-03-13 23:02 UTC, Perederey commented on internal/configuration/configuration.go
> +	c := new(AgentConfiguration)
Var c AgentConfiguration

2023-03-14 06:24 UTC, alphaonly commented on cmd/agent/main.go
> +			break forLabel
Поправил, цикл здесь не нужен

2023-03-14 06:38 UTC, alphaonly commented on cmd/agent/main_test.go
> +			want:  true,
поправил

2023-03-14 06:39 UTC, alphaonly commented on cmd/agent/main.go
> +		case <-ctx.Done():
ok

2023-03-14 06:40 UTC, alphaonly commented on cmd/server/main.go
> +	_server := server.New(configuration, externalStorage, handlers)
поправил

2023-03-14 08:32 UTC, alphaonly commented on cmd/server/main_test.go
> +			name: "test#1 - Positive: server works",
Поправил

2023-03-14 08:43 UTC, alphaonly commented on internal/agent/workerpool/workerpool.go
> +				break forLabel
Потому что воркер получает Job по буферизованному каналу на чтение и выполняет ее и продолжает ждать один из каналов, ждать новой Job, после выполнения переопределяет контекст с дэдлайном, если в течение дэдлайна воркер не получает новый Job или просиходит отмена общего контекста, то происходит break по метке из for.

Если убрать цикл, то worker завершится после выполнения первого задания.

2023-03-14 08:47 UTC, alphaonly commented on internal/configuration/configuration.go
> +	c := new(AgentConfiguration)
поправил

2023-03-14 08:49 UTC, alphaonly commented on internal/configuration/configuration.go
> +	EnvChanged    map[string]bool
ok

2023-03-15 18:30 UTC, Perederey commented
Тесты работают,  теперь все ок

Принимаю работу 👌

2023-03-17 08:27 UTC, Perederey approved these changes
Давай сделаем еще одну итерацию, написал комментарий основные 

Но опять же - автотесты проходят, поэтому работу принимаю. Все замечания больше практические

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/restycheck.go
> +// create HTTP client without redirects support
Посмотри как правильно оформлять комментарии на go effective 
И еще есть Uber go style по коду.
Это тебе поможет еще лучше сделать твой код

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/test.go
> +var f workerpool.TypicalJobFunction = func(data any) workerpool.JobResult {
Data any - считается антипаттерном, если есть возможность исключить его, то лучше исключи.
Может быть тут дженерики лучше?

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/test.go
> +	s := data.(string)
И если используешь привидение к типам,  то лучше вторым параметром сделать еще проверку 

s, ok := data.(string)

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/test.go
> +	wp := workerpool.NewWorkerPool(90, ctx)
Вынеси все 90, константы в config лучше

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/test.go
> +		time.Sleep(5 * time.Second)
От time sleep лучше избавиться, он тебе тут нужен? Может быть лучше заменить на каналы?

2023-03-17 08:27 UTC, Perederey commented on cmd/tests/test.go
> +	wp := workerpool.NewWorkerPool(90, ctx)
И первым параметром контекст, а потом все остальное

2023-03-17 08:27 UTC, Perederey commented on internal/agent/workerpool/workerpool.go
> +type TypicalJobFunction func(data any) JobResult
Идея хорошая, но я бы data any не делал, как писал выше

2023-03-17 08:27 UTC, Perederey commented on internal/agent/workerpool/workerpool.go
> +	context       context.Context
Контекст должен быть не в структуре, а передаваться первым параметром функции

2023-03-17 13:01 UTC, alphaonly commented on internal/agent/workerpool/workerpool.go
> +	context       context.Context
поправил

2023-03-17 13:02 UTC, alphaonly commented on internal/agent/workerpool/workerpool.go
> +type TypicalJobFunction func(data any) JobResult
поправил, сделал на дженериках, но мне нравится первый вариант.

2023-03-17 13:03 UTC, alphaonly commented on cmd/tests/test.go
> +	s := data.(string)
да, точно.  Но убрал, т.к. переделал на дженрерики

2023-03-17 13:03 UTC, alphaonly commented on cmd/tests/test.go
> +var f workerpool.TypicalJobFunction = func(data any) workerpool.JobResult {
поправил, сделал на дженериках

2023-03-17 13:18 UTC, alphaonly commented on cmd/tests/test.go
> +	wp := workerpool.NewWorkerPool(90, ctx)
Поправил

2023-03-17 13:21 UTC, alphaonly commented on cmd/tests/test.go
> +		time.Sleep(5 * time.Second)
забыл убрать. Поправил

2023-05-20 11:30 UTC, merged